//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\SpellCreator.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISpellCreatorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SpellCreatorBaseListener : ISpellCreatorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.spell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpell([NotNull] SpellCreatorParser.SpellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.spell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpell([NotNull] SpellCreatorParser.SpellContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] SpellCreatorParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] SpellCreatorParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.fire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFire([NotNull] SpellCreatorParser.FireContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.fire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFire([NotNull] SpellCreatorParser.FireContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.ice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIce([NotNull] SpellCreatorParser.IceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.ice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIce([NotNull] SpellCreatorParser.IceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.shock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShock([NotNull] SpellCreatorParser.ShockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.shock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShock([NotNull] SpellCreatorParser.ShockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.effect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffect([NotNull] SpellCreatorParser.EffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.effect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffect([NotNull] SpellCreatorParser.EffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.life"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLife([NotNull] SpellCreatorParser.LifeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.life"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLife([NotNull] SpellCreatorParser.LifeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.resistance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResistance([NotNull] SpellCreatorParser.ResistanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.resistance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResistance([NotNull] SpellCreatorParser.ResistanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.speed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeed([NotNull] SpellCreatorParser.SpeedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.speed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeed([NotNull] SpellCreatorParser.SpeedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.shape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShape([NotNull] SpellCreatorParser.ShapeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.shape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShape([NotNull] SpellCreatorParser.ShapeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.projectile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProjectile([NotNull] SpellCreatorParser.ProjectileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.projectile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProjectile([NotNull] SpellCreatorParser.ProjectileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.area"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArea([NotNull] SpellCreatorParser.AreaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.area"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArea([NotNull] SpellCreatorParser.AreaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.self"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelf([NotNull] SpellCreatorParser.SelfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.self"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelf([NotNull] SpellCreatorParser.SelfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.demeanour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDemeanour([NotNull] SpellCreatorParser.DemeanourContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.demeanour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDemeanour([NotNull] SpellCreatorParser.DemeanourContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.instant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstant([NotNull] SpellCreatorParser.InstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.instant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstant([NotNull] SpellCreatorParser.InstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.impulse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImpulse([NotNull] SpellCreatorParser.ImpulseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.impulse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImpulse([NotNull] SpellCreatorParser.ImpulseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.chase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChase([NotNull] SpellCreatorParser.ChaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.chase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChase([NotNull] SpellCreatorParser.ChaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.fall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFall([NotNull] SpellCreatorParser.FallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.fall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFall([NotNull] SpellCreatorParser.FallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.parent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParent([NotNull] SpellCreatorParser.ParentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.parent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParent([NotNull] SpellCreatorParser.ParentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.impact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImpact([NotNull] SpellCreatorParser.ImpactContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.impact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImpact([NotNull] SpellCreatorParser.ImpactContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.destroy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDestroy([NotNull] SpellCreatorParser.DestroyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.destroy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDestroy([NotNull] SpellCreatorParser.DestroyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.ricochet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRicochet([NotNull] SpellCreatorParser.RicochetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.ricochet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRicochet([NotNull] SpellCreatorParser.RicochetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.multiple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiple([NotNull] SpellCreatorParser.MultipleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.multiple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiple([NotNull] SpellCreatorParser.MultipleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellCreatorParser.connector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConnector([NotNull] SpellCreatorParser.ConnectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellCreatorParser.connector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConnector([NotNull] SpellCreatorParser.ConnectorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
